class profile::nfs-server {

	package {'nfs-server':
		name => 'nfs-kernel-server'
	}

	service {'nfs-server':
		name => 'nfs-kernel-server',
		ensure => 'running'
	}

	file {'/etc/exports':
		content => '#### Generated by Puppet.
/home/sites *(rw,sync,subtree_check,all_squash,anonuid=33,anongid=33)',
		require => File['/home/sites'],
		notify => Service['nfs-server']
	}
}